[package]
name = "auto-domain-blocker"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
clap = "3.0.0-beta.5"
anyhow = "1.0"
chrono = "0.4"
